-------------------------------------------------------------
|                   END POINT `/`                           |
-------------------------------------------------------------
### ----------------------------------- HOME
GET http://localhost:50000

-------------------------------------------------------------
|                   END POINT `/users`                      |
-------------------------------------------------------------
### ----------------------------------- Fetch All Users
GET http://localhost:50000/api/users

### ----------------------------------- Get User By ID
GET http://localhost:50000/api/users/1

### ----------------------------------- Create One User
POST http://localhost:50000/api/users
content-type: application/json

{
    "name": "sample",
    "email": "email@email.com",
    "password": "password"
}

### ----------------------------------- Update One User By ID
PUT http://localhost:50000/api/users/1
content-type: application/json

{
    "name": "sample",
    "email": "email@email.com",
    "password": "password"
}

### ----------------------------------- Delete One User
DELETE http://localhost:50000/api/users/1

-------------------------------------------------------------
|                   END POINT `/tasks`                      |
-------------------------------------------------------------
### ----------------------------------- Fetch All Tasks
GET http://localhost:50000/api/tasks

### ----------------------------------- Get Task By ID
GET http://localhost:50000/api/tasks/1

### ----------------------------------- Create One User
POST http://localhost:50000/api/tasks
content-type: application/json

{
    "user_id": "1",
    "title": "Title of Task",
    "description": "lorem ipsum dolor amet"
}

### ----------------------------------- Update One User By ID
PUT http://localhost:50000/api/tasks/1
content-type: application/json

{
    "name": "sample",
    "email": "email@email.com",
    "password": "password"
}

### ----------------------------------- Delete One User
DELETE http://localhost:50000/api/tasks/1